# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Calculator

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: Urijfogul086GTM
    
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Framework
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 1.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build 1.1.4322
    - name: Test
      run: dotnet test --no-build --verbosity normal
